# Site settings
title: Cochise Linux User Group - CLUG
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  We are a volunteer non-profit organization of Linux users from Cochise County,
  Arizona. Our goals are to provide a platform for Linux users to talk with other
  Linux users about their problems and questions, to host presentations from
  members as well as outside individuals about Free and Open Source Software,
  and to expand the use of Linux on personal computers through out the county.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cochiselinux.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  CochiseLinuxUsersGroup

# Build settings
markdown: kramdown
highlighter: rouge
#permalink: /Blog/:title/
timezone: America/Phoenix
paginate: 5

gems:
  - jekyll-feed
  - jekyll-paginate



exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor
  - clug.py
  - install.sh
  - tester.sh
  - contact.html
  - no-sidebar.html
  - left-sidebar.html
  - right-sidebar.html
  - contact.html
